### ISSUE TITLE
浏览器兼容性好差

### ISSUE THREAD

**Issue by xiaozhu188** [vueComponent/ant-design#13]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
...

### Environment
...

### Reproduction link
[example](https://codesandbox.io/s/2wpk21kzvr)

### Steps to reproduce
..

### What is expected?
...

### What is actually happening?
目前测试只有Chrome能运行

---
...

**Comment by lokyoung** [comment]
@xiaozhu188 在Firefox(59)和Safari下测试，都可以正常使用。

**Comment by tangjinzhou** [comment]
如遇低版本浏览器不兼容问题请自行添加 polyfill
https://vuecomponent.github.io/ant-design/docs/vue/getting-started-cn/#%E5%85%BC%E5%AE%B9%E6%80%A7
