### ISSUE TITLE
模态框是否支持显示确定或者取消按钮的其中一个

### ISSUE THREAD

**Issue by ZeroJsus** [vueComponent/ant-design#15]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
...0.4.1

### Environment
...vue2.5.2

### Question
...模态框中能不能指定只显示Ok或者Cancel其中的一个

---
...

**Comment by tangjinzhou** [comment]
可以设置 :footer="null"，然后自定义按钮

**Comment by tangjinzhou** [comment]
http://tangjinzhou.gitee.io/ant-design/components/modal-cn/#components-modal-demo-customized-footer

**Comment by yurizhang** [comment]
404 打不开了，

**Comment by tangjinzhou** [comment]
https://vue.ant.design/components/modal/#components-modal-demo-customize-footer-buttons-props @yurizhang

**Comment by yurizhang** [comment]
谢谢,Modal.confirm里的cancelButtonProps 不起作用.

Modal.confirm里的确认和取消 我想互换位置. 没有找到, 所以我想通过 cancelButtonProps  来设置文本,发现不不起作用.

![image](https://user-images.githubusercontent.com/20555332/56879346-ea460800-6a8a-11e9-845d-c38bddb25112.png)

**Comment by cooperGao** [comment]
> 谢谢,Modal.confirm里的cancelButtonProps 不起作用.
> 
> Modal.confirm里的确认和取消 我想互换位置. 没有找到, 所以我想通过 cancelButtonProps 来设置文本,发现不不起作用.
> 
> ![image](https://user-images.githubusercontent.com/20555332/56879346-ea460800-6a8a-11e9-845d-c38bddb25112.png)

后面解决没有,我也想互换确定和取消的位置

**Comment by ZeroJsus** [comment]
> > 谢谢,Modal.confirm里的cancelButtonProps 不起作用.
> > Modal.confirm里的确认和取消 我想互换位置. 没有找到, 所以我想通过 cancelButtonProps 来设置文本,发现不不起作用.
> > ![image](https://user-images.githubusercontent.com/20555332/56879346-ea460800-6a8a-11e9-845d-c38bddb25112.png)
> 
> 后面解决没有,我也想互换确定和取消的位置

看作者的回复 设置footer为null 然后自定义按钮
