### ISSUE TITLE
table customRow不起作用

### ISSUE THREAD

**Issue by agileago** [vueComponent/ant-design#16]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design/issues) of this repository and believe that this is not a duplicate.
是
### Version
最新

### Environment
chrome

### Reproduction link
[example](https://codesandbox.io/s/p34xq6p57j)

### Steps to reproduce
..

### What is expected?
点击事件应该起效
### What is actually happening?
行点击事件不起作用

---
...

**Comment by tangjinzhou** [comment]
已修复 可升级到0.5.1版本
