### ISSUE TITLE
timeline 组件文字显示不完全

### ISSUE THREAD

**Issue by ZeroJsus** [vueComponent/ant-design#19]
- [ y] I have searched the [issues](https://github.com/vueComponent/ant-design/issues) of this repository and believe that this is not a duplicate.

### [Version]
...vue-antd-ui 0.4.3

### Environment
...vue 2.5.2

### Reproduction link
[example](https://codesandbox.io/s/2wpk21kzvr)
![tim 20180514144623](https://user-images.githubusercontent.com/19191127/39982074-b8fe4938-5785-11e8-856f-d4e5ae9648d3.png)

### Steps to reproduce
... 1.导入antd timeline组件
   2.再页面上使用timeline组件的demo

**Comment by ZeroJsus** [comment]
解决方法: 修改默认的css
>.ant-timeline-item-head{
>    top: 4px;
>}
>.ant-timeline-item-content{
>    top: 0px;
>}

**Comment by tangjinzhou** [comment]
建议查看引用timeline组件的父级元素有无使用overflow: hidden
组件现在是0改动copy的antd，为了方便升级，暂时不考虑修改组件css，
建议你先去给antd提pr
