### ISSUE TITLE
按需引入Form组件提示:Failed to resolve directive: ant-ref

### ISSUE THREAD

**Issue by xiaozhu188** [vueComponent/ant-design#20]
import Vue from 'vue';
import { Button,Form } from 'vue-antd-ui';
Vue.component(Button.name, Button);

Vue.component(Form.name, Form);
Vue.component(Form.Item.name, Form.Item);
复制运行了登录的demo。

**Comment by tangjinzhou** [comment]
Form用到了一个全局指令，导致该提示
两种临时解决方案：
1. 引入Modal组件并注册，这个组件会自动引入指令并注册
2. 手动引入指令并注册
``` html
    import antRefDirective from 'vue-antd-ui/_util/antRefDirective';
    Vue.use(antRefDirective);
```
下个版本0.5.2会添加Form自动注册该指令功能

**Comment by xiaozhu188** [comment]
不用jsx语法如果使用form的验证功能，希望能添加一些demo.

**Comment by xingyys** [comment]
现在有不用jsx语法实现form验证的demo了吗？

**Comment by tangjinzhou** [comment]
http://tangjinzhou.gitee.io/ant-design/components/form-cn/#components-form-demo-customized-validation
但不支持自动校验

**Comment by tangjinzhou** [comment]
问题已解决，可以更新到最新版

**Comment by tangjinzhou** [comment]
ref #103 
如果使用了dll 等  确保 使用的是同一份 vue文件 vue/dist/vue.esm.js
