### ISSUE TITLE
tree组件设置defaultExpandAll 异步获取值的情况下不会自动展开所有节点

### ISSUE THREAD

**Issue by ZeroJsus** [vueComponent/ant-design#21]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
...0.5.1

### Environment
...vue2.5.2

### Reproduction link
[example](https://codepen.io/ZeroJsus/pen/bMmGPE)

### Steps to reproduce
...1.设置a-tree标签
  2.默认的treeNodes值设置为空数组
  3.在mounted组件加载的时候给treeNodes的值赋值

### What is expected?
... 应该是只有第一次获取值不是空的才能正确展开全部节点

**Comment by tangjinzhou** [comment]
defaultExpandAll 仅在组件第一次渲染时有效，不仅仅tree组件，其它组件的defaultXXX值都是这个行为，
可以自行搜索受控组件/非受控组件的概念。
如果你想异步获取数据后展开全部结点，可以使用非受控方式，或[这种方式](https://codepen.io/tangjinzhou/pen/mLzVdN)

**Comment by ZeroJsus** [comment]
谢谢你 你给的例子完美的解决了我的问题
