### ISSUE TITLE
某些组件在旧版IOS上无法使用

### ISSUE THREAD

**Issue by 15010682365** [vueComponent/ant-design#23]
组件版本为："vue-antd-ui": "^0.5.1",

使用环境为：web应用在浏览器中使用，chrome正常，mac safari正常

遇到问题：新版本的ipad浏览器可以正常使用，但在旧版本的ipad，ios9.3.5系统中<a-table><a-data-picker>组件无法显示，<a-row><a-col>格栅中的内容也不能被显示出来，旧版本ipad安装360极速版组件也不能正常表达，初步考虑问题出在了webview上，怎么处理

**Comment by tangjinzhou** [comment]
例如？

**Comment by 15010682365** [comment]
<a-row type="flex" justify="center" align="top">
      <a-col :span="4">A</a-col>
      <a-col :span="4">B</a-col>
      <a-col :span="4">C</a-col>
      <a-col :span="4">D</a-col>
    </a-row>
这样的代码，在旧版本的ipad浏览器中ABCD显示不出来

**Comment by tangjinzhou** [comment]
我这边只能在模拟器下测试，是没有问题的。不排除真实环境有问题，由于精力问题，[antd官方](https://github.com/ant-design/ant-design/issues/1578)也是不支持移动端的(不含ant-design-mobile)，当然你可以提PR修复相关移动端问题。感谢反馈！！！

![image](https://user-images.githubusercontent.com/6937879/40654395-cf377f7a-6370-11e8-8df2-f0b35eff1287.png)
