### ISSUE TITLE
这个项目可以用在生产环境中了吗？

### ISSUE THREAD

**Issue by sunshixiong789** [vueComponent/ant-design#27]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design/issues) of this repository and believe that this is not a duplicate.

### Environment
...

### Reproduction link
[example](https://codesandbox.io/s/2wpk21kzvr)

### Steps to reproduce
..

### What is expected?
如果我想在生产环境中使用？可以吗？你这个能支持多久？

### What is actually happening?
...

---
...

**Comment by tangjinzhou** [comment]
没问题，我们会第一时间解决bug 😄
多久？ 我不确定！希望大家多多使用，多多支持，你们的支持是我们持续维护的动力！！！😁
