### ISSUE TITLE
Should use `Vue.use` to install the library

### ISSUE THREAD

**Issue by lokyoung** [vueComponent/ant-design#3]
首先感谢提供这么棒的ant design的Vue实现。
我已经进行了一些基本的尝试，体验还不错，但是有一个比较头疼的问题，就是每一个组件都需要import之后再使用`Vue.component`进行注册。而且官网上没有直接告诉我们应当导入哪一个组件，怎么去注册。只是给出了一个componen list的链接，在里面你们给出了所有组件的注册示例。所以现在我在开发的时候必须打开这个文件，添加组件的时候去参考里面的内容。使用起来不太方便。
通常情况下在Vue组件库中应当提供install方法注册所有组件，使用者在使用的时候可以直接使用`Vue.use()`去导入整个组件库，不需要每次导入并且指定组件名。

**Comment by nabaonan** [comment]
对的，今天我找菜单组件找了半天，原来是menu里面有item，而且命名不是叫menuitem就叫item，必须把对象打印出来才知道有啥，官网没有说到

**Comment by tangjinzhou** [comment]
下个版本发布时提供
