### ISSUE TITLE
Font Awesome Icons with <Menu>

### ISSUE THREAD

**Issue by go4cas** [vueComponent/ant-design#32]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
0.5.4

### Steps to reproduce
1. Include font-awesome in the app
2. Add a <i> element with a font-awesome class, e.g. `<i class="far fa-clipboard-check" />` inside a `<MenuItem>`

### What is expected?
Render icon only when the `<Sider>` is collapsed

### What is actually happening?
Icon is rendered correctly when the `<Sider>` is expanded
When collapsed, however, part of the menu item text is still visible.

**Comment by tangjinzhou** [comment]
Can you provide a demo like [this](https://codesandbox.io/s/2wpk21kzvr)?

**Comment by go4cas** [comment]
Here's simple sample: https://codesandbox.io/s/6ykz7w2ppn

**Comment by tangjinzhou** [comment]
The display of text has a certain relationship with Icon's [class](https://github.com/vueComponent/ant-design/blob/master/components/menu/style/index.less#L380) name.
But, You can use like [this](https://codesandbox.io/s/r453x5rlpn)

**Comment by go4cas** [comment]
That'll work just fine. Thanks!
