### ISSUE TITLE
Cannot read property 'querySelectorAll' of undefined

### ISSUE THREAD

**Issue by DragonT** [vueComponent/ant-design#33]
Cannot read property 'querySelectorAll' of undefined
`<a-table rowKey='id' :columns="columns" :scroll="{ x: 1900,y:700 }" :dataSource="data"  :loading='loadingData' @change="handleChange"  :rowSelection="{selectedRowKeys: selectedRowKeys, onChange: onSelectChange}"/>`
去掉
`:loading='loadingData' @change="handleChange"  :rowSelection="{selectedRowKeys: selectedRowKeys, onChange: onSelectChange}"` 就不会出现这个错误

**Comment by tangjinzhou** [comment]
参考[这个](https://codesandbox.io/s/2wpk21kzvr)给一个复现问题的在线示例吧 
多谢反馈！

**Comment by DragonT** [comment]
https://codesandbox.io/s/ym14978zlj   这个时候表头和固定列会出现滚动条

**Comment by DragonT** [comment]
@tangjinzhou 感谢大佬能开源这么好的作品，可不可以提一个小小的建议 现在的Form组件太react，可不可以像iview或element那样简单点。

**Comment by tangjinzhou** [comment]
Form组件暂时不会有大的改动
关于vue jsx的使用可以查看 https://zhuanlan.zhihu.com/p/37920151
