### ISSUE TITLE
defaultExpandedRowKeys不能展开所有行defaultExpandAllRows也用不了方法写错了。

### ISSUE THREAD

**Issue by JulesCesar** [vueComponent/ant-design#36]
我这边放不上图片不知道咋回事儿。
<a-table 
                                style="margin-right:24px;" 
                                :columns="columns" 
                                :dataSource="data" 
                                :rowSelection="rowSelection" 
                                bordered 
                                rowKey='id' 
                                :pagination='pagination'  
                                :expandedRowKeys = "rowstr"
                                :indentSize='indentSize'
                                :hideDefaultSelections='hideDefaultSelections'
                                
                                >
 rowstr(){
                return this.data.map(val=>val.id)
            }

用的这个解决的expandedRowKeys
查一下吧

**Comment by tangjinzhou** [comment]
并没有问题  https://codesandbox.io/s/nrpl7pjl3l
请按照issue模板，提供复现问题demo

**Comment by yy303023858** [comment]
可能是异步过来的数据，默认展开不好使吧，我的也是。

**Comment by tangjinzhou** [comment]
defaultXXX是组件第一次实例化时才会生效，具体原理参照react的受控组件/非受控组件
