### ISSUE TITLE
Select选择器的使用

### ISSUE THREAD

**Issue by loliconer** [vueComponent/ant-design#37]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design/issues) of this repository and believe that this is not a duplicate.

### 描述
现在的select选择器使用起来感觉有点冗余，是否可以简化一下？

### 现在
```
<a-select v-model="value">
    <a-select-option v-for="option of options"
        :value="option.value" :key="option.value">{{option.label}}</a-select-option>
</a-select>
```

### 可以这样?
```
<a-select v-model="value" :data-source="options"></a-select>
```

### What is actually happening?
...

---
...

**Comment by tangjinzhou** [comment]
👌 后期会考虑，你也可以给我们提pr

**Comment by jasonc08** [comment]
如果用了你简化了的版本，我怎样才可以改变select-option里面的内容
现在的是比较好，一看便了解怎样用

**Comment by loliconer** [comment]
@jasonc08 
1. 你为什么需要改变option里的内容？其实对于使用者来说并不关心option部分；
2. 每个组件都需要看doc的，这里只要约定好value和label两个属性即可，就像table的数据约定了title和dataIndex；
3. doc只需看一次，一劳永逸，你这样每次都得多写这么多代码，不够简洁

@tangjinzhou 不好意思啊，对jsx语法不是很熟悉，看了下源码，select组件的代码结构有点复杂，不知道怎么下手[捂脸]。如果没时间的话可以以后再说的，毕竟只是个小改进，并不影响使用。

**Comment by chenchi2038** [comment]
感觉现在的写法更加灵活，也方便订制。

**Comment by tangjinzhou** [comment]
https://github.com/vueComponent/ant-design/commit/f3791aaafebcee5a8719899b03b1b24fa28a96c1#diff-77f08012e52de8332c20210da6cbe3adL38
