### ISSUE TITLE
引用menu的时候会报错:  Menu children not support undefined

### ISSUE THREAD

**Issue by xuzixiang** [vueComponent/ant-design#38]
![image](https://user-images.githubusercontent.com/30492854/41456540-5cf1d0f0-70b3-11e8-8ed3-5ed933e6637d.png)

**Comment by xuzixiang** [comment]
大牛能否帮忙看看这个问题呢 , 不知道是不是我用的不对 , 采用的例子是文档上提供的最简单的那种

**Comment by tangjinzhou** [comment]
Menu.Item未注册

**Comment by xuzixiang** [comment]
好吧 , 问题解决了 , 谢谢大牛
