### ISSUE TITLE
Row组件报错

### ISSUE THREAD

**Issue by glauca** [vueComponent/ant-design#39]
Chrome使用正常，Firefox ESR 45.9 & IE 11 `Row组件`报错

##### 文字子节点，正常显示 

    <a-row type="flex" justify="center" align="top">
      AAAAA
    </a-row>

##### 组件子节点，Firefox ESR 45.9 & IE 11报错

    <a-row type="flex" justify="center" align="bottom">
      <a-icon type="area-chart" />
    </a-row>

![_20180617114253](https://user-images.githubusercontent.com/8234015/41504497-88c6502e-71e0-11e8-984e-1018e1e59cf3.png)

**Comment by tangjinzhou** [comment]
请自行添加 Object.entries polyfill   
可参考https://github.com/babel/babel/issues/3036
