### ISSUE TITLE
当a-select或者a-input-number 组件 绑定了 v-model 时，placeholder属性不起作用

### ISSUE THREAD

**Issue by zycFran** [vueComponent/ant-design#44]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
 "vue-antd-ui": "^0.5.4"

### Environment
...

### Reproduction link
[example](https://codesandbox.io/s/2wpk21kzvr)

### Steps to reproduce
..

### What is expected?
...

### What is actually happening?
...

---
...

**Comment by tangjinzhou** [comment]
麻烦给出具体复现bug的具体demo链接 谢谢

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/n0wz4z8p4m
使用undefined作为初始值，因为空字符在select中是有意义的

**Comment by bq-hentai** [comment]
@tangjinzhou got it, thx
