### ISSUE TITLE
固钉在 <router-view></router-view> 中会异常

### ISSUE THREAD

**Issue by fastgoo** [vueComponent/ant-design#45]
### 版本：
0.6.1
### 问题：
在router-view中 通过菜单push，按钮正常
![image](https://user-images.githubusercontent.com/15431129/41815250-fdd7af68-7797-11e8-83fd-897c922e0ce4.png)

点击浏览器刷新
![image](https://user-images.githubusercontent.com/15431129/41815261-429834c4-7798-11e8-894b-d3a8e83f259b.png)

**Comment by tangjinzhou** [comment]
请给出链接 谢谢
PS: 是否有会影响组件的样式文件是动态异步加载

**Comment by webees** [comment]
一定要把vue升级到最新版本，2.5.0版本vue还会导致侧边栏切换，展开菜单收缩动画异常抖动的情况。
