### ISSUE TITLE
求带单元格编辑功能的表格。的API详细的

### ISSUE THREAD

**Issue by JulesCesar** [vueComponent/ant-design#47]
例如如何配置一行多个可编辑的并不是全部编辑。

**Comment by JulesCesar** [comment]
就是我只编辑  name 和age怎么设置

**Comment by tangjinzhou** [comment]
这是你业务层面的东西，组件没有相关API，可参考如下demo：
http://tangjinzhou.gitee.io/ant-design/components/table-cn/#components-table-demo-editable-cells

**Comment by JulesCesar** [comment]
我知道 这个例子！现在是只有name的行内编辑  如果我想让age也可以编辑的话怎么设置？

**Comment by JulesCesar** [comment]
表格里的hover如何拿掉？
