### ISSUE TITLE
[Bug Report] Popover代码演示章节，点击从浮层内关闭的【Click me】按钮无反应

### ISSUE THREAD

**Issue by caryYin** [vueComponent/ant-design#49]
### Version
0.6.2

### Environment
win7/ Chrome,FireFox

### Reproduction link
none

### Steps to reproduce
https://vuecomponent.github.io/ant-design/components/popover-cn/

### What is expected?
Popover代码演示章节，点击从浮层内关闭的【Click me】按钮无反应

### What is actually happening?
弹出气泡式的卡片浮层。

**Comment by tangjinzhou** [comment]
多谢反馈  可升级到0.6.3版本
https://github.com/vueComponent/ant-design/releases/tag/0.6.3
