### ISSUE TITLE
导入组件好变扭

### ISSUE THREAD

**Issue by nabaonan** [vueComponent/ant-design#5]
现在需要一个一个导入，希望作者能够跟elelement一样，一句话导入

**Comment by wangxueliang** [comment]
@nabaonan 不知道理解清楚你的意思没，你是希望一次导入多个文件？可以通过multiple属性控制是否支持多选文件，默认是false

**Comment by tangjinzhou** [comment]
下个版本发布时会提供，不过还是建议不要一起导入，
可以使用[按需加载](https://vuecomponent.github.io/ant-design/docs/vue/introduce-cn/#%E6%8C%89%E9%9C%80%E5%8A%A0%E8%BD%BD)尽量减少体积

**Comment by renshuo** [comment]
我们的产品在内网中运行，所以不需要担心性能问题，还是希望能够支持一次性全部导入的功能。

**Comment by tangjinzhou** [comment]
https://github.com/vueComponent/ant-design/releases/tag/0.4.0
