### ISSUE TITLE
【 FEATURE】momentjs后面是否有可能换成dayjs

### ISSUE THREAD

**Issue by webees** [vueComponent/ant-design#50]
群友介绍了dayjs，发现这个组件比momentjs轻量，且api与momentjs一样。
想了解下是否可能换为momentjs。如果不会的话我就自己单独调整修改。

**Comment by tangjinzhou** [comment]
暂时不会，
内部有一些类型判断，你自己调整的话，内部类型判断不通过
当然你可以查看源码，自行hack绕过去
