### ISSUE TITLE
【建议】能否支持一个输入框的双日历显示

### ISSUE THREAD

**Issue by caryYin** [vueComponent/ant-design#51]
### Version
0.63

### What is expected?
类似这种：
![default](https://user-images.githubusercontent.com/9817765/41952944-4a672bdc-7a05-11e8-905b-c856b1132ab2.png)

**Comment by tangjinzhou** [comment]
你指的这些？
https://vuecomponent.github.io/ant-design/components/date-picker/

**Comment by caryYin** [comment]
是的，能否显示成这样吗，非RangePicker
![default](https://user-images.githubusercontent.com/9817765/41955000-c4ca3954-7a10-11e8-9e09-1b1bff3b4040.png)

**Comment by tangjinzhou** [comment]
抱歉  暂不支持
