### ISSUE TITLE
Warnings when using Form

### ISSUE THREAD

**Issue by kajeagentspi** [vueComponent/ant-design#52]
### 请严格按照如下模板反馈bug，尤其是复现bug的demo链接，不合规范的issue会被立刻关闭！！！

- [x] I have searched the [issues](https://github.com/vueComponent/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
0.6.3

### Environment
node 8.11.2

### Steps to reproduce
add a form
### What is expected?
no warning
### What is actually happening?
```
 WARNING  Compiled with 2 warnings                                        14:25:37

 warning  in ./node_modules/vue-antd-ui/es/form/index.js

"export 'FormComponentProps' was not found in './Form'

 warning  in ./node_modules/vue-antd-ui/es/form/index.js

"export 'ValidateCallback' was not found in './Form'
```

---

The missing exports is not really in ./Form

**Comment by tangjinzhou** [comment]
Thank you for your feedback.
In the next version I will remove them.

**Comment by kajeagentspi** [comment]
Ok thanks
