### ISSUE TITLE
Change a-input-search v-model's output to String

### ISSUE THREAD

**Issue by kajeagentspi** [vueComponent/ant-design#53]
### 请严格按照如下模板反馈bug，尤其是复现bug的demo链接，不合规范的issue会被立刻关闭！！！

- [X] I have searched the [issues](https://github.com/vueComponent/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[example](https://codesandbox.io/s/2wpk21kzvr)

### Steps to reproduce
add an a-input-search with a v-model

### What is expected?
v-model value would be string

### What is actually happening?
v-model's value is an object containing the event

---
...

**Comment by tangjinzhou** [comment]
please update to 0.6.4
https://github.com/vueComponent/ant-design/releases/tag/0.6.4
