### ISSUE TITLE
固定表头 会导致表头不见了

### ISSUE THREAD

**Issue by JulesCesar** [vueComponent/ant-design#54]
![image](https://user-images.githubusercontent.com/19618696/42031533-20fb35cc-7b09-11e8-8493-5a246ca63952.png)

**Comment by JulesCesar** [comment]
![image](https://user-images.githubusercontent.com/19618696/42031682-bd5c5f4a-7b09-11e8-8fca-246c41a75eb5.png)

**Comment by JulesCesar** [comment]
![image](https://user-images.githubusercontent.com/19618696/42031719-d8abc9c0-7b09-11e8-9f78-27bf285bb2af.png)

**Comment by JulesCesar** [comment]
表头不见了 去掉scroll就会表头出来

**Comment by tangjinzhou** [comment]
请严格按照模板提issue 谢谢
