### ISSUE TITLE
固定表头 添加scroll后会导致表头不见

### ISSUE THREAD

**Issue by JulesCesar** [vueComponent/ant-design#55]
### Version
"vue-antd-ui": "^0.5.4"

### Environment
node 8.11.2

### Reproduction link
No link

###Problem
只要往表格里面放入:scroll="{ y: 240 }"，就会出现表头消失不见。
![image](https://user-images.githubusercontent.com/19618696/42034001-3845d036-7b11-11e8-915c-6da013c03bb9.png)

我试过将此链接整个代码原封不动拿入工程
https://vuecomponent.github.io/ant-design/components/table-cn/#components-table-demo-fixed-header
运行结果依然是无表头 去掉scroll表头出现如下图
![image](https://user-images.githubusercontent.com/19618696/42034082-7ee9c56a-7b11-11e8-948d-f8f7565aaa1f.png)

**Comment by tangjinzhou** [comment]
在这个链接(https://codesandbox.io/s/2wpk21kzvr)demo基础上
给一个复现你问题的链接,谢谢

**Comment by JulesCesar** [comment]
已解决！层级的事儿

**Comment by mdramos** [comment]
@JulesCesar Did you find any issues with the way the headers aligned with the table body?

In my scroll table, the headers do not align. It is fixed when I remove the `scroll` attribute. Ive tried adjusting code and all and I cant seem to figure it out.

example of the problem:
<img width="818" alt="screen shot 2018-08-19 at 9 36 04 pm" src="https://user-images.githubusercontent.com/7244317/44316142-1091af00-a3f8-11e8-9b63-0852b5187b7f.png">

**Comment by mdramos** [comment]
nvm. width with % works, but not exactly ideal
