### ISSUE TITLE
为啥没有走马灯的组件？

### ISSUE THREAD

**Issue by ChenKaiKe** [vueComponent/ant-design#58]
### 请严格按照如下模板反馈bug，尤其是复现bug的demo链接，不合规范的issue会被立刻关闭！！！

- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version2.0
...

### Environment
...node8.9.3,npm 6.1.0,win8.1

### Reproduction link
[example](https://codesandbox.io/s/2wpk21kzvr)

### Steps to reproduce
..

### What is expected?
...

### What is actually happening?
...

---
...

**Comment by tangjinzhou** [comment]
正在开发中...
走马灯组件可以先选择其他第三方组件，
如下有部分相关组件可选择：
https://github.com/vuejs/awesome-vue#carousel

感谢关注，我们会尽快开发。
