### ISSUE TITLE
这个自定义主题采用them的方式，这个配置过程很模糊，可以详细点吗？

### ISSUE THREAD

**Issue by ChenKaiKe** [vueComponent/ant-design#60]
### 请严格按照如下模板反馈bug，尤其是复现bug的demo链接，不合规范的issue会被立刻关闭！！！

- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
...

### Environment
...

### Reproduction link
[example](https://codesandbox.io/s/2wpk21kzvr)

### Steps to reproduce
..

### What is expected?
...

### What is actually happening?
...

---
...

**Comment by tangjinzhou** [comment]
更多主题配置的问题可以参考react版的[antd](http://ant-design.gitee.io/docs/react/customize-theme-cn#1)-theme-%E5%B1%9E%E6%80%A7%EF%BC%88%E6%8E%A8%E8%8D%90%EF%BC%89)
使用方法都是一样的。
