### ISSUE TITLE
Upload组件的问题

### ISSUE THREAD

**Issue by fengqinglingyu** [vueComponent/ant-design#61]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
0.6.5

### Environment
WIN7 X64 Chrome 67

### Reproduction link
[example](https://codesandbox.io/s/0q384z062l)

### Steps to reproduce
这个是官网给的例子，手动上传的，首先，选择一个文件，控制台会报两个错误
Invalid prop: custom validator check failed for prop "fileList".
Invalid prop: custom validator check failed for prop "items".
如果删除这个文件的话，没法删除，控制台会报
Error in event handler for "remove": "TypeError: Cannot read property 'fileList' of undefined" 

### What is expected?
请尽快修复这个问题

### What is actually happening?
官网给的例子，只要设置了beforeUpload这个属性，选择文件都会报
Invalid prop: custom validator check failed for prop "items".
至于那个fileList的问题，是最后一个官网例子出错的

**Comment by tangjinzhou** [comment]
@wangxueliang

**Comment by dingyiming** [comment]
+1 遇到一样的报错，希望尽快修复，谢谢

**Comment by tangjinzhou** [comment]
可升级到0.6.6
https://github.com/vueComponent/ant-design/releases/tag/0.6.6

**Comment by fengqinglingyu** [comment]
这么快修复了，点赞！
