### ISSUE TITLE
locale-provider lost Transfer.title property

### ISSUE THREAD

**Issue by weifu2** [vueComponent/ant-design#64]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
0.6.7

### Environment
1

### Reproduction link
[https://github.com/vueComponent/ant-design](https://github.com/vueComponent/ant-design)

### Steps to reproduce
use locale-provider/zh_CN.js，then test Transfer,  find errors if don't use :title property

### What is expected?
no errors

### What is actually happening?
in components/transfer/index.jsx, use "titleText={titles[0]} and title[1]" if no title is specified, but only in en_US.js，we had the Transfer.title property, you lost the Transfer.title property in other languares

**Comment by tangjinzhou** [comment]
please update to 0.6.8
https://github.com/vueComponent/ant-design/releases/tag/0.6.8
