### ISSUE TITLE
Do not require action prop for upload

### ISSUE THREAD

**Issue by kajeagentspi** [vueComponent/ant-design#66]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
0.6.8

### Environment
Latest

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/130nn5omvj)

### Steps to reproduce
Remove the action prop because you've setup a customRequest or you mapped the upload to an @change event

### What is expected?
No errors

### What is actually happening?

![image](https://user-images.githubusercontent.com/15797424/42494518-1c3d9720-8453-11e8-9a14-16fe51759371.png)

**Comment by tangjinzhou** [comment]
please update to 0.7.0
https://github.com/vueComponent/ant-design/releases/tag/0.7.0
