### ISSUE TITLE
Tooltip Containing Select: [Vue warn]: Error in event handler for "blur": "TypeError: Cannot read property 'relatedTarget' of undefined"

### ISSUE THREAD

**Issue by Festbawi** [vueComponent/ant-design#67]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
0.6.8

### Environment
Latest

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nk89rmj7vl)

### Steps to reproduce
1. Hover over select
2. Look at console: Vue warn
3. Blur select (un-hover)

### What is expected?
No warnings

### What is actually happening?
Warnings

![image](https://user-images.githubusercontent.com/8520418/42550693-cba68a48-8505-11e8-921a-776dfc3184f4.png)

**Comment by tangjinzhou** [comment]
please update to 0.7.0
https://github.com/vueComponent/ant-design/releases/tag/0.7.0
