### ISSUE TITLE
less引用方式报错

### ISSUE THREAD

**Issue by liuqz** [vueComponent/ant-design#68]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
0.7.0

### Environment
archlinux X64, chromium 67, Vue 2.5.16, less 3.0.4, less-loader 4.1.0

### Reproduction link
[http://localhost:8080](http://localhost:8080)

### Steps to reproduce
```
import Antd from 'vue-antd-ui'
import 'vue-antd-ui/dist/antd.less'
```
**yarn serve 就报错**
```
ERROR  Failed to compile with 1 errors                                                                                                                                              9:12:43 PM

error  in ./node_modules/vue-antd-ui/dist/antd.less

Module build failed (from ./node_modules/less-loader/dist/cjs.js):


// https://github.com/ant-design/ant-motion/issues/44
.bezierEasingMixin();
^
```

### What is expected?
引用less文件，覆写样式

### What is actually happening?
引用就报错

**Comment by tangjinzhou** [comment]
less-loader添加 {javascriptEnabled: true}

**Comment by tangjinzhou** [comment]
更多可参考
https://github.com/ant-design/ant-design/issues/7927

**Comment by tangjinzhou** [comment]
如何修改Ant Design of Vue主题色？ - 择卡的回答 - 知乎
https://www.zhihu.com/question/284811056/answer/440370119

**Comment by liuqz** [comment]
你这个回答是针对vue-cli 2.X的，vue-cli 3.x的配置文件变了，没有build/utils.js这个目录的配置了，只能通过vue.config.js或package.json配置。

**Comment by liuqz** [comment]
是我错了，module.exports少写了个s。谢谢！

**Comment by XINXINP** [comment]
1.在vue.config.js文件里配置
module.export = {
    css: {
        loaderOptions: {
            less: {
                javascriptEnabled: true
            }
        }
    }
}
2.降低vue-cli 版本号
