### ISSUE TITLE
异步请求数据，设置分页失效

### ISSUE THREAD

**Issue by nabaonan** [vueComponent/ant-design#70]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
0.7.0

### Environment
windows10  chrome67.0.3396.99  vue2.5.16

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ywo1n76x51)

### Steps to reproduce
ajax请求后台数据，返回数据设置分页的total，不生效

### What is expected?
希望分页可以根据异步请求返回的total进行分页

### What is actually happening?
分页无法生效

**Comment by tangjinzhou** [comment]
当前版本(0.7.0)pagination属性不支持 deep watch,
你可以使用
this.pagination = { ...this.pagination, total: 100 }; 
替换  this.pagination.total = 100;
下个版本会添加支持deep watch

**Comment by Fournny** [comment]
> this.pagination.total = 100;

现在还得这样设置才生效：this.pagination.total = 100;  以下无效：  
const page = { ..._this.pagination }
        page.total = result.totalRow

版本：~1.3.7

**Comment by iisquare** [comment]
踩坑，打卡
