### ISSUE TITLE
Card 组件文档有误

### ISSUE THREAD

**Issue by tortorse** [vueComponent/ant-design#71]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
0.7.0

### Environment
windows 10, chrome 67

### Reproduction link
[https://vuecomponent.github.io/ant-design/components/card-cn/#](https://vuecomponent.github.io/ant-design/components/card-cn/#)

### Steps to reproduce
线上文档有误，文档中的 `reactNode` 概念在vue中不存在。

### What is expected?
可以是一个局部 render 方法， 也可以是一个具名slot

### What is actually happening?
不知道如何传递 reactNode 给组件

**Comment by tangjinzhou** [comment]
done
