### ISSUE TITLE
用tamplate方式实现表单form的表单项的添加与删除有问题

### ISSUE THREAD

**Issue by ChenKaiKe** [vueComponent/ant-design#74]
- 问题：
tamplate方式实现表单form的表单项的添加与删除，添加没有问题，删除的时候会出现以下问题：
1.删除表单项后，在次提交表单，获取的值还是有以前已经删除的表单项的值在；
2.删除不是最后项的时候，后面的表单项的值会被清空，可是提交表单的时候，后面表单的值还在。
代码：
tamplate:
<a-form :autoFormCreate="(form)=>{this.form = form}" style="margin: 0 0 !important;" class="clearfix" @submit="submitForm">
<a-form-item
				      v-for="(item,index) in companyList"
				      :key="index"
				      :fieldDecoratorId="'name['+item+']'"
				    >
				      <a-input placeholder='input placeholder' class="dy_input"/>
				       {{item}}
				      <a-icon
				      	  v-if="companyList.length>1"
			              class='dynamic-delete-button'
			              type='minus-circle-o'
			              @click="remove(item)"
			            />
				    </a-form-item>
</a-form-item>
- script:
export default {
	name: 'report',
	data () {
		return  {
			uid: 0,
			companyList: [],
			uuid: 0,
		}
	},
	mounted () {
		console.log('form==',this.form)
		this.init()
	},
	compouted: {
//		companyList () {
//			return this.companyList
//		}
	},
	methods: {
		submitForm (e) {
		  	let that = this
		    e.preventDefault()
		    console.log('111')
		    that.form.validateFields((err, values) => {
		    	if (!err) {
		       		console.log('Received values of form: ', values);
		    	}
	      	})
	    },
	    remove  (item) {
	       let that = this
//	       let companyList = that.companyList
//	       let arr = companyList.filter(company => company != item)
//	       that.companyList = arr
//	       console.log("remove===",that.companyList)

	      const keys = that.form.getFieldValue('companyList')
	      if (keys.length === 1) {
	        return
	      }
	      that.form.setFieldsValue({
	        companyList: keys.filter(key => key != item),
	      })
		  that.companyList = that.form.getFieldValue('companyList')
		  console.log("remove11=",that.form.getFieldValue('companyList'))
		  console.log("re=",that.companyList)
	    },
	    add () {
	      let that = this
//	      that.companyList.push(that.uuid)
//	      that.uuid = that.uuid+1
//	      console.log("add=",that.companyList)
	      
	      const keys = that.form.getFieldValue('companyList')
	      const nextKeys = keys.concat(that.uuid)
	      that.uuid = that.uuid+1
	      // can use data-binding to set
	      // important! notify form to detect changes
	      that.form.setFieldsValue({
	        companyList: nextKeys,
	      })
	      that.companyList = that.form.getFieldValue('companyList')
	       console.log("add_nex=",nextKeys)
	      console.log("add=",that.companyList)
	      
	    },
	    init () {
	    	let that = this
	    	that.form.getFieldDecorator('companyList', { initialValue: [] })
	    }
	}
}

**Comment by tangjinzhou** [comment]
请使用  https://vuecomponent.github.io/vue-antd-issue-helper/ 创建issue
