### ISSUE TITLE
用tamplate方式实现表单form的表单项的添加与删除有问题

### ISSUE THREAD

**Issue by ChenKaiKe** [vueComponent/ant-design#75]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
0.7.1

### Environment
lastest

### Reproduction link
[![Edit Vue Template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/y062234or9)

### Steps to reproduce
1.使用tamplate方式使用form表单
2.参考官网实现表单项的添加与删除

### What is expected?
1.删除表单项后，提交表单，应该没有已经删除的表单项的值
2..删除不是最后项的时候，后面的表单项应该不变

### What is actually happening?
1.删除表单项后，在次提交表单，获取的值还是有以前已经删除的表单项的值在；
2..删除不是最后项的时候，后面的表单项的值会被清空，可是提交表单的时候，后面表单的值还在。

**Comment by tangjinzhou** [comment]
Reproduction link ?

**Comment by tangjinzhou** [comment]
给一个复现你bug的demo链接？

**Comment by ChenKaiKe** [comment]
我是在本地弄的，就是很简单的一个vue的tamplate，是这样的
tamplate:
<a-form :autoFormCreate="(form)=>{this.form = form}" style="margin: 0 0 !important;" class="clearfix" @submit="submitForm">


{{item}}
<a-icon
v-if="companyList.length>1"
class='dynamic-delete-button'
type='minus-circle-o'
@click="remove(item)"
/>
- script: export default { name: 'report', data () { return { uid: 0, companyList: [], uuid: 0, } }, mounted () { console.log('form==',this.form) this.init() }, compouted: { //	companyList () { // return this.companyList //	} }, methods: { submitForm (e) { let that = this e.preventDefault() console.log('111') that.form.validateFields((err, values) => { if (!err) { console.log('Received values of form: ', values); } }) }, remove (item) { let that = this //	let companyList = that.companyList //	let arr = companyList.filter(company => company != item) //	that.companyList = arr // console.log("remove===",that.companyList)
      const keys = that.form.getFieldValue('companyList')
      if (keys.length === 1) {
        return
      }
      that.form.setFieldsValue({
        companyList: keys.filter(key => key != item),
      })
	  that.companyList = that.form.getFieldValue('companyList')
	  console.log("remove11=",that.form.getFieldValue('companyList'))
	  console.log("re=",that.companyList)
    },
    add () {
      let that = this
//	that.companyList.push(that.uuid)
//	that.uuid = that.uuid+1
//	console.log("add=",that.companyList)

      const keys = that.form.getFieldValue('companyList')
      const nextKeys = keys.concat(that.uuid)
      that.uuid = that.uuid+1
      // can use data-binding to set
      // important! notify form to detect changes
      that.form.setFieldsValue({
        companyList: nextKeys,
      })
      that.companyList = that.form.getFieldValue('companyList')
       console.log("add_nex=",nextKeys)
      console.log("add=",that.companyList)
      
    },
    init () {
    	let that = this
    	that.form.getFieldDecorator('companyList', { initialValue: [] })
    }
}

**Comment by ChenKaiKe** [comment]
我是在本地弄的，就是很简单的一个vue的tamplate，是这样的
tamplate:
<a-form :autoFormCreate="(form)=>{this.form = form}" style="margin: 0 0 !important;" class="clearfix" @submit="submitForm">


{{item}}
<a-icon
v-if="companyList.length>1"
class='dynamic-delete-button'
type='minus-circle-o'
@click="remove(item)"
/>
- script: export default { name: 'report', data () { return { uid: 0, companyList: [], uuid: 0, } }, mounted () { console.log('form==',this.form) this.init() }, compouted: { //	companyList () { // return this.companyList //	} }, methods: { submitForm (e) { let that = this e.preventDefault() console.log('111') that.form.validateFields((err, values) => { if (!err) { console.log('Received values of form: ', values); } }) }, remove (item) { let that = this //	let companyList = that.companyList //	let arr = companyList.filter(company => company != item) //	that.companyList = arr // console.log("remove===",that.companyList)
      const keys = that.form.getFieldValue('companyList')
      if (keys.length === 1) {
        return
      }
      that.form.setFieldsValue({
        companyList: keys.filter(key => key != item),
      })
	  that.companyList = that.form.getFieldValue('companyList')
	  console.log("remove11=",that.form.getFieldValue('companyList'))
	  console.log("re=",that.companyList)
    },
    add () {
      let that = this
//	that.companyList.push(that.uuid)
//	that.uuid = that.uuid+1
//	console.log("add=",that.companyList)

      const keys = that.form.getFieldValue('companyList')
      const nextKeys = keys.concat(that.uuid)
      that.uuid = that.uuid+1
      // can use data-binding to set
      // important! notify form to detect changes
      that.form.setFieldsValue({
        companyList: nextKeys,
      })
      that.companyList = that.form.getFieldValue('companyList')
       console.log("add_nex=",nextKeys)
      console.log("add=",that.companyList)
      
    },
    init () {
    	let that = this
    	that.form.getFieldDecorator('companyList', { initialValue: [] })
    }
}

**Comment by ChenKaiKe** [comment]
我是在本地弄的，就是很简单的一个vue的tamplate，是这样的
tamplate:
<a-form :autoFormCreate="(form)=>{this.form = form}" style="margin: 0 0 !important;" class="clearfix" @submit="submitForm">


{{item}}
<a-icon
v-if="companyList.length>1"
class='dynamic-delete-button'
type='minus-circle-o'
@click="remove(item)"
/>
- script: export default { name: 'report', data () { return { uid: 0, companyList: [], uuid: 0, } }, mounted () { console.log('form==',this.form) this.init() }, compouted: { //	companyList () { // return this.companyList //	} }, methods: { submitForm (e) { let that = this e.preventDefault() console.log('111') that.form.validateFields((err, values) => { if (!err) { console.log('Received values of form: ', values); } }) }, remove (item) { let that = this //	let companyList = that.companyList //	let arr = companyList.filter(company => company != item) //	that.companyList = arr // console.log("remove===",that.companyList)
      const keys = that.form.getFieldValue('companyList')
      if (keys.length === 1) {
        return
      }
      that.form.setFieldsValue({
        companyList: keys.filter(key => key != item),
      })
	  that.companyList = that.form.getFieldValue('companyList')
	  console.log("remove11=",that.form.getFieldValue('companyList'))
	  console.log("re=",that.companyList)
    },
    add () {
      let that = this
//	that.companyList.push(that.uuid)
//	that.uuid = that.uuid+1
//	console.log("add=",that.companyList)

      const keys = that.form.getFieldValue('companyList')
      const nextKeys = keys.concat(that.uuid)
      that.uuid = that.uuid+1
      // can use data-binding to set
      // important! notify form to detect changes
      that.form.setFieldsValue({
        companyList: nextKeys,
      })
      that.companyList = that.form.getFieldValue('companyList')
       console.log("add_nex=",nextKeys)
      console.log("add=",that.companyList)
      
    },
    init () {
    	let that = this
    	that.form.getFieldDecorator('companyList', { initialValue: [] })
    }
}

**Comment by ChenKaiKe** [comment]
我是在本地弄的，就是很简单的一个vue的tamplate，是这样的
tamplate:
<a-form :autoFormCreate="(form)=>{this.form = form}" style="margin: 0 0 !important;" class="clearfix" @submit="submitForm">


{{item}}
<a-icon
v-if="companyList.length>1"
class='dynamic-delete-button'
type='minus-circle-o'
@click="remove(item

**Comment by ChenKaiKe** [comment]
我是在本地弄的，就是很简单的一个vue的tamplate，是这样的
tamplate:
<a-form :autoFormCreate="(form)=>{this.form = form}" style="margin: 0 0 !important;" class="clearfix" @submit="submitForm">


{{item}}
<a-icon
v-if="companyList.length>1"
class='dynamic-delete-button'
type='minus-circle-o'
@click="remove(item

**Comment by tangjinzhou** [comment]
不要使用index作为key

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/0yx470kjxl
