### ISSUE TITLE
AutoComplete 自动完成组件，select后，能执行blur事件吗？

### ISSUE THREAD

**Issue by caryYin** [vueComponent/ant-design#76]
### What problem does this feature solve?
现在选中后，光标还在输入框里面，能提供功能，光标不在输入框里面吗？就是选中后，能blur出输入框吗？

### What does the proposed API look like?
列表中选中一项后，能blur出输入框。

当前效果：
![image](https://user-images.githubusercontent.com/9817765/42864334-a9585d20-8a98-11e8-92a5-ce5892bce44a.png)

希望实现的效果：
![image](https://user-images.githubusercontent.com/9817765/42864355-b80401b2-8a98-11e8-8af3-96ed3ec90482.png)

**Comment by tangjinzhou** [comment]
this.$refs.XXX.blur()

**Comment by caryYin** [comment]
在@select事件里执行this.$refs.XXX.blur()之后，还是会focus，并进到focus()方面里面。

**Comment by tangjinzhou** [comment]
请提供在线demo
