### ISSUE TITLE
表单项为inputGroup时候，表单验证失效

### ISSUE THREAD

**Issue by nabaonan** [vueComponent/ant-design#78]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.0.0

### Environment
windows10  chrome67.0.3396.99  vue2.5.16

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rjlnynjrvn)

### Steps to reproduce
1使用自定义校验，点击提交，只会校验一次，
2使用自带的required:true,校验失效,值变化，但是验证错误依然存在

### What is expected?
希望使用自定义校验，点击提交之后，每次都可以走校验而不是只第一次进行校验
最好是设置required为true时候输入框校验也可以生效

### What is actually happening?
自定义校验和required为true校验均未生效

**Comment by tangjinzhou** [comment]
> 如果使用template语法，可以使用autoFormCreate开启自动校验和数据收集功能，但每一个Form.Item仅仅对其第一个子组件进行decorator。更加复杂的功能建议使用JSX。

http://tangjinzhou.gitee.io/ant-design/components/form-cn/#autoFormCreate
inputGroup包含input和select，form.item并不能准确定位你要decorator哪一个  

对于这种情况你可以使用更加灵活的jsx
或自定义校验

**Comment by nabaonan** [comment]
我用了自定义校验，但是每次都只会调用一次

**Comment by tangjinzhou** [comment]
自定义校验  
https://codesandbox.io/s/6v081nl413
