### ISSUE TITLE
cannot open webpage about avatar with chrome

### ISSUE THREAD

**Issue by aotemanzhuangui** [vueComponent/ant-design#79]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.0.0

### Environment
windows chrome version 67.0.3396.87

### Reproduction link
[http://tangjinzhou.gitee.io/ant-design/components/avatar-cn/](http://tangjinzhou.gitee.io/ant-design/components/avatar-cn/)

### Steps to reproduce
input the url,not open

### What is expected?
open the webpage

### What is actually happening?
cannot open the webpage

**Comment by tangjinzhou** [comment]
I don't have this problem.
You can clear cache and refresh
Or use https://vuecomponent.github.io/ant-design/components/avatar/
