### ISSUE TITLE
menu在收起的情况下@click事件会报错，@select却不会报错但是无法取到父级的subkey

### ISSUE THREAD

**Issue by fastgoo** [vueComponent/ant-design#8]
如题

**Comment by tangjinzhou** [comment]
基于这个[模板](https://codesandbox.io/s/2wpk21kzvr)给我一个复现的链接吧

**Comment by tangjinzhou** [comment]
https://github.com/vueComponent/ant-design/commit/3694ad80c78042099d1249eb1a67f4f53cb80056
