### ISSUE TITLE
组件 Card.Meta 属性description和title 的类型问题

### ISSUE THREAD

**Issue by iczer** [vueComponent/ant-design#83]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
官方API文档中 Card.Meta 属性description和title 类型为slot，但查看源码后发现该属性实际为String。希望更新此属性类型为slot。

### What does the proposed API look like?
期望API同文档保持一致

**Comment by tangjinzhou** [comment]
都支持的

**Comment by iczer** [comment]
目前vue-antd-ui版本1.0.0，Card.meta 里 slot="description" 组件无法显示，不知什么原因。如下，description组件无法显示：
```html
 <a-card :hoverable="true">
  <a-card-meta :title="item.title">
    <a-avatar class="card-avatar" slot="avatar" :src="item.avatar" size="large" />
    <div slot="description">{{item.content}}</div>
  </a-card-meta>
  <ul class="ant-card-actions" slot="actions">
     <li><a >操作一</a></li>
     <li><a >操作二</a></li>
  </ul>
 </a-card>
```

**Comment by tangjinzhou** [comment]
@wangxueliang

**Comment by iczer** [comment]
附上显示效果图，图中标记处应该显示slot:description组件，实际没有渲染：
![image](https://user-images.githubusercontent.com/13096697/43303573-e66c0f2a-91a2-11e8-82f3-8f4780c4f07b.png)

**Comment by tangjinzhou** [comment]
[8560f0](https://github.com/vueComponent/ant-design/commit/8560f0eb48f55879535604ed5d9fb0e5a068fcfb)

**Comment by tangjinzhou** [comment]
[8560f0](https://github.com/vueComponent/ant-design/commit/8560f0eb48f55879535604ed5d9fb0e5a068fcfb)

**Comment by iczer** [comment]
感谢

**Comment by tangjinzhou** [comment]
https://github.com/vueComponent/ant-design/releases/tag/1.0.1
