### ISSUE TITLE
时间组件弹出窗添加自定义类名没有生效

### ISSUE THREAD

**Issue by sjhleo** [vueComponent/ant-design#85]
`<a-range-picker
      :defaultValue="[moment('2015-06-06', dateFormat), 
      moment('2015-06-06', dateFormat)]"
      disabled 
      dropdownClassName="diy-class"
 />`

 组件弹出的日历窗口没有带上diy-class,dropdownClassName属性未生效

**Comment by tangjinzhou** [comment]
1.0.1已经修复
