### ISSUE TITLE
部分组件IE9兼容问题

### ISSUE THREAD

**Issue by sjhleo** [vueComponent/ant-design#86]
组件对IE9兼容有些小问题，page组件和modal模态框组件、alert、message、notification、在IE9环境下表现均不正常。

**Comment by tangjinzhou** [comment]
方便详细说明吗  是报错还是样式  …

**Comment by sjhleo** [comment]
@tangjinzhou 样式问题 弹窗在ie中都跑到页面下方去了,内容错位

**Comment by tangjinzhou** [comment]
我并不能复现你描述的问题
现在官方站点已经兼容ie9，可查看官方demo
如还有问题可使用[issue-helper](https://vuecomponent.github.io/vue-antd-issue-helper/?lang=zh)严格遵照规范提issue，多谢
