### ISSUE TITLE
菜单嵌套样式丢失，点击无效

### ISSUE THREAD

**Issue by mcmf** [vueComponent/ant-design#89]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.0.1

### Environment
mac,chrome

### Reproduction link
[http://noexample.com](http://noexample.com)

### Steps to reproduce
```
<a-menu
:defaultSelectedKeys="['1']"
:defaultOpenKeys="['sub1']"
mode="inline"
theme="dark"
>
<menu-list v-for="itemlist in menus"></menu-list>
</a-menu>

menuList.vue

<a-menu-item>
.....
</a-menu-item>

```

### What is expected?
这样引用就会有问题，样式也丢了 事件也不对了

### What is actually happening?
如果动态循环生成菜单，比如根据路由 就无法如此处理    或者怎么处理 
![image](https://user-images.githubusercontent.com/19700237/43366333-f8416434-936e-11e8-9b81-cae3d8388c75.png)
生成的菜单：
![image](https://user-images.githubusercontent.com/19700237/43366340-1d1bcdda-936f-11e8-9b2e-46c2ee932a36.png)

。还有一个bug   如果使用menuList.vue  组件加载
![image](https://user-images.githubusercontent.com/19700237/43366312-9a52ccfa-936e-11e8-9fad-2e2005fbd50c.png)

a layout slider  包裹一个 a menu   包裹一个menuList  组件 就会报
Invalid prop: custom validator check failed for prop "action". found
in
---> <Trigger>
<ASubMenu>
<SidebarItem> at
src/views/ layout/ components/MenuList. vue

![image](https://user-images.githubusercontent.com/19700237/43366313-a01b9432-936e-11e8-9ac5-c8af8017900e.png)

**Comment by tangjinzhou** [comment]
1. 多个问题请分开提issue
2. 请给出复现bug链接 
谢谢

**Comment by pql** [comment]
<a-layout-sider
      :trigger="null"
      collapsible
      :collapsed="isCollapse"
      :style="{ overflow: 'auto', height: '100vh', position: 'fixed', left: 0 }"
      :width="180"
      :collapsedWidth="80"
    >
      <div class="logo" />
      <a-menu 
        theme="dark" 
        mode="inline" >
         <div>
            <a-menu-item key="1">
              <a-icon type="pie-chart" />
               <span>Option 1</span>
            </a-menu-item>
         </div>
      </a-menu>
    </a-layout-sider>
只要往a-menu-item或者是a-sub-menu标签外套一层，就会出现上面的问题

**Comment by tangjinzhou** [comment]
menu的直接子元素只可以是menuItem或subMenu
