### ISSUE TITLE
a-range-picker中的defaultValue不能正确执行

### ISSUE THREAD

**Issue by feng9217** [vueComponent/ant-design#90]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.0.1

### Environment
chrome , vue 2.9.X

### Reproduction link
[https://jsfiddle.net/mmx38qxw/4412/](https://jsfiddle.net/mmx38qxw/4412/)

### Steps to reproduce
抱歉在线链接只能把整个组件搬上来了 在使用日期选择器的时候 设置默认值出现了浏览器报错
首先是 Property or method "moment" is not defined 但是我在created的时候打印了 moment() 是正确引入了的(PS: 已经确认并不是moment加载前组件渲染不正确的问题)
其次 我把传入值改成 :defaultValue="[start_day, end_day]" 想撇开moment自己控制时间的之后 又会返回 传入的props不正确的报错

### What is expected?
a-range-picker 组件的defaultValue能正确使用

### What is actually happening?
报错了

---
希望可以自己传入 [开始时间, 结束时间] 这样

**Comment by tangjinzhou** [comment]
1. 你使用的模板语法，在模板中moment的确是未定义的，没毛病
2. 值仅支持moment类型，不能任意传递其它类型

**Comment by feng9217** [comment]
import 后 在data里声明一次 .....
想到了 ..
3Q

**Comment by gitspringcould** [comment]
有代码示例吗
