### ISSUE TITLE
Use both "Collapsed inline menu" and "Open current submenu only" occurs submenu floats.

### ISSUE THREAD

**Issue by myronlau** [vueComponent/ant-design#91]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.0.1

### Environment
OS: Windows 10 Browser: Chrome 67.0.3396.99 Vue: 2.9.6

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/32jnjvollp)

### Steps to reproduce
1. The menu can be collapsed
2. Add the function " onOpenChange" to make it open current submenu only

### What is expected?
When I click the "Collapsed inline menu" button, no submenu items floats immediately.

### What is actually happening?
As the title, submenu items floats immediately when I click the "Collapsed inline menu" button

**Comment by tangjinzhou** [comment]
```
watch: {
    collapsed(val){
      if(val) {
        this.openKeys = []
      }
    }
  },
```
https://codesandbox.io/s/yw1nxmm3jx
