### ISSUE TITLE
a-calendar组件渲染数据问题

### ISSUE THREAD

**Issue by feng9217** [vueComponent/ant-design#94]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.0.1

### Environment
chrome , vue 2.9.X

### Reproduction link
[https://jsfiddle.net/eywraw8t/232300/ && https://jsfiddle.net/eywraw8t/232359/](https://jsfiddle.net/eywraw8t/232300/ && https://jsfiddle.net/eywraw8t/232359/)

### Steps to reproduce
感觉应该会写得有点长, 麻烦大佬慢慢看一下哈, 3Q .....
业务应该是异步获取一个当前月份对应天数的数据, 对应哪些天数应该渲染
代码链接: https://jsfiddle.net/eywraw8t/232300/
我自己写了一个假数据以后, 出现了和文档demo同样的情况, 那就是下个月在当前日历显示出来的日期上也渲染上了数据
PS: 此时getListData() 还只是将所有展现的日期遍历了一遍
于是乎我想到的解决办法就是 定义一个数组 把已经有过数据的日期添加到数组中 若日期已经在数组中的 就不再添加数据了
代码链接: https://jsfiddle.net/eywraw8t/232359/
这时候就出现了一个新的问题 那就是加上了这一层判断以后 v-for="item in getListData(value)" 从结果上来看遍历了两次
第一次 成功的赋值 并且也屏蔽了重复日期的赋值
但是第二次遍历的时候 就把所有赋的值给抹去了
所以看似是运行成功了 实际上在calendar上没有产生任何结果

### What is expected?
calendar能正常的渲染数据并且不产生重复日期的赋值

### What is actually happening?
出现了鱼和熊掌的问题

---
麻烦帮看一下 或者是否有别的实现业务的方法 ??

**Comment by tangjinzhou** [comment]
参考[demo](https://jsfiddle.net/f79zLh86/5/) 给出可运行的demo链接

**Comment by feng9217** [comment]
https://codesandbox.io/s/pwx0q6wq07 
demo来啦 ~
麻烦了 3Q~

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/o5opmz82kz

这是你业务功能实现的问题

**Comment by feng9217** [comment]
完美解决了 !! 谢谢 !!
