### ISSUE TITLE
table组件样式bug

### ISSUE THREAD

**Issue by liuqz** [vueComponent/ant-design#97]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.0.1

### Environment
vue2.5.16

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/886wz9l0r2)

### Steps to reproduce
文档table组件示例固定头和列在firefox下样式错行。
中间列过少的话，固定列会出现两列，见例子

### What is expected?
表格正常

### What is actually happening?
表格样式错误

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/8ryjnmr09

另外可参考antd相关issue  
[#11328](https://github.com/ant-design/ant-design/issues/11328)

- 你需要自行控制列宽度的和与 scroll.x 匹配。
- 如果列宽度之和是个固定值，那么两者最好相等。
- 如果列宽度之和小于 scroll.x，那么最好留一列或几列不设宽度，用于弹性适应剩余宽度。

**Comment by liuqz** [comment]
中间列要根据选项不同自动生成。谢谢

**Comment by liuqz** [comment]
火狐下固定头和列样式错行还没解决，怎么就关了呢？

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/44133635-56463c4a-a093-11e8-851c-d457d2394517.png)
所以这是什么意思？
然后12天之后你告诉我没解决

**Comment by liuqz** [comment]
两个问题，你只解决了一个，还问我什么意思？看内容就这么粗心啊。

**Comment by iczer** [comment]
实测，为columns fixed属性导致的bug。
去除后fixed后正常显示：
[![Edit Vue Template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vmm356wz3l)

**Comment by iczer** [comment]
实测为columns fixed属性导致的bug，去除fixed属性后正常显示：
[![Edit Vue Template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vmm356wz3l)

**Comment by tangjinzhou** [comment]
呵呵   element iview 欢迎你

**Comment by liuqz** [comment]
我给你报文档显示问题，你让我走，好吧！
